Adding support for the new production-test-framework python package
* Updated tests to use the new package
* The tests now run outside of a container, so the old docker compose
  and container based test commands have been removed
* Now referencing the python package from the production-test-framework
  git repo
* Updated documentation to refelct the new behavior

Signed-off-by: Tom Hurtt <tom@delosdata.com>

diff --git a/tests/Makefile b/tests/Makefile
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -6,37 +6,51 @@ MOSAIC_PATH ?= $(abspath ..)
 export MOSAIC_PATH
 
 RESULTS_DIR ?= $(HOME)/tmp/mosaic
+TESTS_DIR ?= $(MOSAIC_PATH)/tests/suites
+TEST_MARKER ?= "profiler_otel or dashboards"
 
 FRAMEWORK_SERVICE_NAME ?= production-test-framework
 FRAMEWORK_CONTAINER_NAME ?= production-test-framework
 
-.PHONY: setup run-tests copy-test-results test cleanup
+UV_INSTALL_URL ?= https://docs.astral.sh/uv/getting-started/installation/
+
+.PHONY: check-uv setup run-tests copy-test-results test cleanup
 
 # These targets should not stop the make workflow if they fail
 .IGNORE: copy-test-results
 
+check-uv:
+	@command -v uv >/dev/null 2>&1 || { \
+		echo ""; \
+		echo "********************************************************************************"; \
+		echo "Error: uv is not installed or not in the PATH."; \
+		echo "You can install uv from:"; \
+		echo "$(UV_INSTALL_URL)"; \
+		echo "********************************************************************************"; \
+		echo ""; \
+		exit 1; \
+	}
+
+# Start the container stack
 setup:
 	@echo "Starting container stack..."
-	@docker compose --profile="*" pull && \
-	docker compose up -d
+	docker compose -f $(MOSAIC_PATH)/deployments/docker-compose.yml -f $(MOSAIC_PATH)/deployments/docker-compose-vllm.yml up --wait -d --pull always
 
 cleanup:
 	@echo "Cleaning up container stack..."
-	@docker compose --profile "*" down --remove-orphans \
+	@docker compose -f $(MOSAIC_PATH)/deployments/docker-compose.yml -f $(MOSAIC_PATH)/deployments/docker-compose-vllm.yml down --remove-orphans \
 	&& docker container prune -f
 
-run-tests:
-	docker compose run --name $(FRAMEWORK_CONTAINER_NAME) $(FRAMEWORK_SERVICE_NAME) 
+# Run the tests and exit with the pytest exit code
+run-tests: check-uv
+	@echo "$(TASK) Running tests with marker: $(TEST_MARKER)..."; \
+	cd $(TESTS_DIR) && \
+	uv run pytest -m $(TEST_MARKER) --junitxml=$(RESULTS_DIR)/test_results.xml -v .; \
+	exit $$?;
 
-copy-test-results:
-	rm -rf $(RESULTS_DIR)
-	mkdir -p $(RESULTS_DIR) \
-	&& docker cp $(FRAMEWORK_CONTAINER_NAME):/app/results/test_results.xml $(RESULTS_DIR)/test_results.xml
-
-# Run the tests and copy the results to the results directory
-test: setup
+# Start the container stack, run the tests, and clean up
+test: check-uv setup
 	@$(MAKE) run-tests; EXIT_CODE=$$?; echo "EXIT_CODE: $$EXIT_CODE"; \
-	$(MAKE) copy-test-results; \
 	$(MAKE) cleanup; \
 	exit $$EXIT_CODE
 
